version: 2
updates:
- package-ecosystem: uv
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  assignees:
    - "uriyyo"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
